dist: trusty
sudo: required
language: php

services:
- docker

env:
  global:
  - DOCKER_COMPOSE_VERSION=1.27.4

before_script:
- make install-phars
- if [ "$INTEGRATION_TEST" == "enabled" ]; then sudo rm -f /usr/local/bin/docker-compose; fi;
- if [ "$INTEGRATION_TEST" == "enabled" ]; then curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose; fi;
- if [ "$INTEGRATION_TEST" == "enabled" ]; then chmod +x docker-compose; fi;
- if [ "$INTEGRATION_TEST" == "enabled" ]; then sudo mv docker-compose /usr/local/bin; fi;
- if [ "$INTEGRATION_TEST" == "enabled" ]; then make platform; fi;
- composer self-update --2
- if [ "$DEPENDENCIES" == "stable" ]; then composer update --prefer-stable; fi;
- if [ "$DEPENDENCIES" == "low" ]; then composer update --prefer-lowest --prefer-stable; fi;

script:
- if [ "$INTEGRATION_TEST" == "enabled" ]; then COMPOSER=composer PHP=php make phpunit-integration ; else COMPOSER=composer PHP=php make ci-local; fi;

jobs:
  include:
  - stage: test
    php: '7.3'
    env: DEPENDENCIES="low" TOOL="phpunit"
    script: COMPOSER=composer PHP=php make phpunit
  - php: '7.4'
    env: DEPENDENCIES="low" TOOL="phpunit"
    script: COMPOSER=composer PHP=php make phpunit
  - php: 'nightly'
    env: DEPENDENCIES="low" TOOL="phpunit"
    script: COMPOSER=composer PHP=php make phpunit
  - env: DEPENDENCIES="stable" TOOL="phpunit"
    php: '7.3'
    script: COMPOSER=composer PHP=php make phpunit
  - env: DEPENDENCIES="stable" TOOL="phpunit"
    php: '7.4'
    script: COMPOSER=composer PHP=php make phpunit
  - env: DEPENDENCIES="stable" TOOL="phpunit"
    php: 'nightly'
    script: COMPOSER=composer PHP=php make phpunit
  - env: DEPENDENCIES="stable" TOOL="phpstan"
    php: '7.3'
    script: COMPOSER=composer PHP=php make phpstan
  - env: DEPENDENCIES="stable" TOOL="phpstan"
    php: '7.4'
    script: COMPOSER=composer PHP=php make phpstan
  - env: DEPENDENCIES="stable" TOOL="phpstan"
    php: 'nightly'
    script: COMPOSER=composer PHP=php make phpstan
  - env: DEPENDENCIES="stable" TOOL="php-cs-fixer"
    php: '7.3'
    script: COMPOSER=composer PHP=php make cs-fixer
  - env: DEPENDENCIES="stable" TOOL="php-cs-fixer"
    php: '7.4'
    script: COMPOSER=composer PHP=php make cs-fixer
  - stage: integration
    php: '7.4'
    env: DEPENDENCIES="stable" INTEGRATION_TEST="enabled" CONFLUENT_VERSION="4.1.4"
  - env: DEPENDENCIES="stable" INTEGRATION_TEST="enabled" CONFLUENT_VERSION="5.5.2"
    php: '7.4'
  - env: DEPENDENCIES="stable" INTEGRATION_TEST="enabled" CONFLUENT_VERSION="latest"
    php: '7.4'
  - stage: coverage
    php: '7.3'
    env:
    - DEPENDENCIES="stable" TOOL="coverage"
    script:
    - PHP=php make coverage

after_script:
- make clean

branches:
  only:
  - master
  - '/^ft-.*/'
  - '/^v\d+\.\d+\.\d+$/'

cache:
  directories:
    - $HOME/.composer/cache/files
    - vendor
