name: "PHP Confluent Serde CI Checks"
on:
  pull_request:
    branches:
      - master
      - ft/**
jobs:
  export-docker:
    strategy:
      matrix:
        php:
          -
            version: 7.4
            xdebug: 2.9.8
          -
            version: 7.3
            xdebug: 2.9.8
          -
            version: rc
            xdebug: 3.0.0beta1
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          load: true
          tags: php-avro-serde:${{ matrix.php.version }}
          build-args: |
            PHP_VERSION=${{ matrix.php.version }}
            XDEBUG_VERSION=${{ matrix.php.xdebug }}
      -
        name: Inspect docker image
        run: |
          docker image inspect php-avro-serde:${{ matrix.php.version }}
      -
        name: Save docker image
        run: |
          docker image save php-avro-serde:${{ matrix.php.version }} -o php-avro-serde-${{ matrix.php.version }}.tgz
      -
        name: Upload docker image
        uses: actions/upload-artifact@v2
        with:
          name: php-avro-serde-${{ matrix.php.version }}
          path: php-avro-serde-${{ matrix.php.version }}.tgz
